package org.dam.programacion.ejercicios.estructuras.control;

public class caracteresUnicode {

    // IZQUIERDA
    private static final String LADO_SUPERIOR_IZQUIERDA = "┌";
    private static final String LADO_CENTRAL_IZQUIERDA = "├";
    private static final String LADO_INFERIOR_IZQUIERDA = "└";

    // INTERSECCIONES
    private static final String INTERSECCION_SUPERIOR = "┬";
    private static final String INTERSECCION_CENTRAL = "┼";
    private static final String INTERSECCION_INFERIOR = "┴";

    // LINEAS
    private static final String LINEA_HORIZONTAL = "─";
    private static final String LINEA_VERTICAL = "│";

    // DERECHA
    private static final String LADO_SUPERIOR_DERECHA = "┐";
    private static final String LADO_CENTRAL_DERECHA = "┤";
    private static final String LADO_INFERIOR_DERECHA = "┘";

    // CASILLAS
    private static final String CASILLA_NEGRA = "█";
    private static final String CASILLA_BLANCA = "░";


    public static void main(String[] args) {
        //CUADRADO CON DOS CASILLAS
        System.out.println(LADO_SUPERIOR_IZQUIERDA + LINEA_HORIZONTAL + LINEA_HORIZONTAL + LADO_SUPERIOR_DERECHA);
        System.out.println(LINEA_VERTICAL + CASILLA_BLANCA + CASILLA_NEGRA + LINEA_VERTICAL);
        System.out.println(LADO_INFERIOR_IZQUIERDA + LINEA_HORIZONTAL + LINEA_HORIZONTAL + LADO_INFERIOR_DERECHA);

        //CUADRADO CON CUATRO CASILLAS
        System.out.println(LADO_SUPERIOR_IZQUIERDA + LINEA_HORIZONTAL + LINEA_HORIZONTAL + INTERSECCION_SUPERIOR + LINEA_HORIZONTAL + LINEA_HORIZONTAL + LADO_SUPERIOR_DERECHA);
        System.out.println(LINEA_VERTICAL + CASILLA_BLANCA + CASILLA_NEGRA + LINEA_VERTICAL + CASILLA_BLANCA + CASILLA_NEGRA + LINEA_VERTICAL);
        System.out.println(LADO_CENTRAL_IZQUIERDA + LINEA_HORIZONTAL + LINEA_HORIZONTAL + INTERSECCION_CENTRAL + LINEA_HORIZONTAL + LINEA_HORIZONTAL + LADO_CENTRAL_DERECHA);
        System.out.println(LINEA_VERTICAL + CASILLA_BLANCA + CASILLA_NEGRA + LINEA_VERTICAL + CASILLA_BLANCA + CASILLA_NEGRA + LINEA_VERTICAL);
        System.out.println(LADO_INFERIOR_IZQUIERDA + LINEA_HORIZONTAL + LINEA_HORIZONTAL + INTERSECCION_INFERIOR + LINEA_HORIZONTAL + LINEA_HORIZONTAL + LADO_INFERIOR_DERECHA);

        //CUADRADO CON NUEVE CASILLAS
        System.out.println(LADO_SUPERIOR_IZQUIERDA + LINEA_HORIZONTAL + LINEA_HORIZONTAL + INTERSECCION_SUPERIOR + LINEA_HORIZONTAL +  LINEA_HORIZONTAL + INTERSECCION_SUPERIOR + LINEA_HORIZONTAL + LINEA_HORIZONTAL +LADO_SUPERIOR_DERECHA);
        System.out.println(LINEA_VERTICAL + CASILLA_BLANCA + CASILLA_NEGRA + LINEA_VERTICAL + CASILLA_BLANCA + CASILLA_NEGRA + LINEA_VERTICAL+ CASILLA_BLANCA + CASILLA_NEGRA + LINEA_VERTICAL);
        System.out.println(LADO_CENTRAL_IZQUIERDA + LINEA_HORIZONTAL + LINEA_HORIZONTAL + INTERSECCION_CENTRAL + LINEA_HORIZONTAL + LINEA_HORIZONTAL + LADO_CENTRAL_DERECHA +  LINEA_HORIZONTAL + LINEA_HORIZONTAL + LADO_CENTRAL_DERECHA);
        System.out.println(LINEA_VERTICAL + CASILLA_BLANCA + CASILLA_NEGRA + LINEA_VERTICAL + CASILLA_BLANCA + CASILLA_NEGRA + LINEA_VERTICAL+ CASILLA_BLANCA + CASILLA_NEGRA + LINEA_VERTICAL);
        System.out.println(LADO_CENTRAL_IZQUIERDA + LINEA_HORIZONTAL + LINEA_HORIZONTAL + INTERSECCION_CENTRAL + LINEA_HORIZONTAL + LINEA_HORIZONTAL + LADO_CENTRAL_DERECHA +  LINEA_HORIZONTAL + LINEA_HORIZONTAL + LADO_CENTRAL_DERECHA);
        System.out.println(LINEA_VERTICAL + CASILLA_BLANCA + CASILLA_NEGRA + LINEA_VERTICAL + CASILLA_BLANCA + CASILLA_NEGRA + LINEA_VERTICAL+ CASILLA_BLANCA + CASILLA_NEGRA + LINEA_VERTICAL);
        System.out.println(LADO_INFERIOR_IZQUIERDA + LINEA_HORIZONTAL + LINEA_HORIZONTAL + INTERSECCION_INFERIOR + LINEA_HORIZONTAL + LINEA_HORIZONTAL + INTERSECCION_INFERIOR + LINEA_HORIZONTAL + LINEA_HORIZONTAL +LADO_INFERIOR_DERECHA);
    }
}
