name: Compilar proyectos Java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      className:
        description: 'Nombre de la clase con main a ejecutar'
        required: false

jobs:
  build:
  # Job 1: Construcción en cada push
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4
      # Paso 2: Configuración del JDK
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23' 
          distribution: 'temurin'
          cache: maven
          
      # Paso 3: Construcción con Maven
      - name: Build with Maven
        run: mvn -B clean package --file Programacion/javaBasics/pom.xml
        
      # Paso 4: Obtener el nombre de la clase principal y renombrar el JAR
      - name: Get main class and rename JAR
        id: get_jar_name
        run: |
          MAIN_CLASS=$(mvn help:effective-pom --file Programacion/javaBasics/pom.xml | grep "mainClass" | tail -n 1 | awk -F '[<>]' '{print $3}' | awk -F '.' '{print $(NF)}' | awk '{sub(/Vacio$/, ""); print}')
          echo "jar_name=$MAIN_CLASS" >> $GITHUB_ENV
          echo "The JAR name is: $MAIN_CLASS"

      # Paso 5: Guardar el JAR como artefacto
      - name: Save JAR file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.jar_name }}
          path: Programacion/javaBasics/target/*.jar
          

  # Job 2: Ejecución del archivo .jar (depende del job 'build')
  execute:
    runs-on: ubuntu-latest
    needs: build  # Solo se ejecuta si el job 'build' es exitoso

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
         name: ${{ env.jar_name }} # Usar el nombre de clase si se proporciona
         
      - name: Run specified Java Application
        run: |
          JAR_FILE=$(find . -name "*.jar" | head -n 1)
          if [ -z "$JAR_FILE" ]; then
            echo "No se encontró ningún archivo JAR."
            exit 1
          fi
          echo "Ejecutando: $JAR_FILE"
          java -jar "$JAR_FILE"

  # Job 3: Dependency Review en pull requests
  dependency_review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file Programacion/javaBasics/pom.xml
        # Paso 4: Subir dependency graph para Dependabot
      - name: Dependency graph submission
        uses: actions/dependency-review-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
